[window]

opacity = 0.8

[font]

normal = { family = "Mononoki Nerd Font", style = "Regular" }
bold = { family = "Mononoki Nerd Font", style = "Bold" }
italic = { family = "Mononoki Nerd Font", style = "Italic" }
size = 12
