# Habilitar soporte de True Color dentro de tmux
set -g default-terminal "xterm-256color"
set -ga terminal-overrides ",xterm-256color:Tc"

# Cambiar el prefijo a Ctrl+a (más cómodo que Ctrl+b)
unbind C-b
set-option -g prefix C-a
bind-option C-a send-prefix

# Atajos nativos tipo Vim para moverte entre paneles
bind h select-pane -L
bind j select-pane -D
bind k select-pane -u
bind l select-pane -R

# Habilitar el ratón por si acaso
set -g mouse on
